'use client';

import * as React from 'react';
import { useRouter } from 'next/navigation';
import { buildFlatList, FlatItem } from '@/lib/curriculum';
import { useUiStore } from '@/stores/ui-store';
import { toast } from 'sonner';

interface MarkdownRendererProps {
  html: string;
}

// ─── DOM processing extracted outside the component ──────────────────────────
// This runs after dangerouslySetInnerHTML has committed (via rAF).

async function processMermaid(
  container: HTMLElement,
  setDiagramSvg: (svg: string | null) => void,
) {
  const codeBlocks = container.querySelectorAll('code.language-mermaid');
  if (codeBlocks.length === 0) return;

  const mermaidNodes: HTMLDivElement[] = [];

  codeBlocks.forEach((codeEl) => {
    const pre = codeEl.closest('pre');
    if (!pre) return;

    const rawCode = (codeEl.textContent || '').trim();

    // Outer wrapper
    const wrapper = document.createElement('div');
    wrapper.className = 'my-6 border border-border/30 rounded-lg overflow-hidden bg-bg-elev/40 shadow-sm w-full max-w-full';

    // Header bar
    const header = document.createElement('div');
    header.className = 'flex items-center justify-between px-4 py-2 border-b border-border/20 bg-bg-elev2/60 text-[11px] font-mono select-none';
    header.innerHTML = `
      <span class="text-text-dim font-semibold tracking-wider uppercase">System Diagram</span>
      <button class="toggle-btn text-accent hover:text-accent-2 font-bold transition-colors cursor-pointer text-[11px]">View Source</button>
    `;

    // White diagram panel
    const diagramContainer = document.createElement('div');
    diagramContainer.className = 'diagram-panel p-6 bg-white flex justify-center overflow-x-auto w-full max-w-full min-w-0';
    diagramContainer.style.position = 'relative';

    const diagramInner = document.createElement('div');
    diagramInner.className = 'mermaid-inner w-full min-w-0 flex justify-center';
    diagramInner.textContent = rawCode;
    diagramContainer.appendChild(diagramInner);

    // Raw source fallback panel
    const sourceContainer = document.createElement('pre');
    sourceContainer.className = 'source-panel p-4 overflow-x-auto text-[13px] font-mono bg-bg-elev hidden';
    sourceContainer.textContent = rawCode;

    wrapper.appendChild(header);
    wrapper.appendChild(diagramContainer);
    wrapper.appendChild(sourceContainer);

    // Insert into DOM BEFORE mermaid runs
    pre.replaceWith(wrapper);

    // Toggle source/diagram
    const toggleBtn = header.querySelector('.toggle-btn') as HTMLButtonElement;
    toggleBtn.addEventListener('click', (e) => {
      e.stopPropagation();
      const showingSource = !sourceContainer.classList.contains('hidden');
      if (showingSource) {
        sourceContainer.classList.add('hidden');
        diagramContainer.classList.remove('hidden');
        toggleBtn.textContent = 'View Source';
      } else {
        sourceContainer.classList.remove('hidden');
        diagramContainer.classList.add('hidden');
        toggleBtn.textContent = 'View Diagram';
      }
    });

    mermaidNodes.push(diagramInner);
  });

  if (mermaidNodes.length === 0) return;

  try {
    const m = await import('mermaid');
    const mermaid = m.default;

    mermaid.initialize({
      startOnLoad: false,
      theme: 'default',
      securityLevel: 'loose',
      fontFamily: 'ui-sans-serif, system-ui, sans-serif',
      flowchart: { useMaxWidth: true },
      sequence: { useMaxWidth: true },
      gantt: { useMaxWidth: true },
      journey: { useMaxWidth: true },
      class: { useMaxWidth: true },
      state: { useMaxWidth: true },
      er: { useMaxWidth: true },
      pie: { useMaxWidth: true },
    });

    for (let i = 0; i < mermaidNodes.length; i++) {
      const node = mermaidNodes[i];
      const source = node.textContent || '';
      if (!source.trim()) continue;
      if (node.querySelector('svg')) continue; // already rendered (StrictMode double-invoke guard)

      const renderId = `mermaid-${Date.now()}-${i}-${Math.random().toString(36).slice(2, 8)}`;

      try {
        const { svg } = await mermaid.render(renderId, source);
        node.innerHTML = svg;

        const svgEl = node.querySelector('svg');
        if (svgEl) {
          // Read native max-width from style or attributes generated by Mermaid
          let intrinsicWidth = svgEl.style.maxWidth;
          if (!intrinsicWidth || intrinsicWidth === '100%') {
            const wAttr = svgEl.getAttribute('width');
            if (wAttr && !wAttr.endsWith('%')) {
              intrinsicWidth = wAttr.includes('px') ? wAttr : `${wAttr}px`;
            }
          }
          if (!intrinsicWidth) {
            const viewBox = svgEl.getAttribute('viewBox');
            if (viewBox) {
              const parts = viewBox.split(/\s+/);
              if (parts.length >= 3) {
                intrinsicWidth = `${parts[2]}px`;
              }
            }
          }

          svgEl.removeAttribute('width');
          svgEl.style.width = '100%';
          svgEl.style.height = 'auto';
          svgEl.style.display = 'block';
          svgEl.style.margin = '0 auto';
          if (intrinsicWidth) {
            svgEl.style.maxWidth = intrinsicWidth;
          } else {
            svgEl.style.maxWidth = '100%';
          }
        }

        // Click-to-expand
        const diagramPanel = node.closest('.diagram-panel') as HTMLElement;
        if (diagramPanel) {
          diagramPanel.style.cursor = 'zoom-in';

          // Hover hint badge
          const hint = document.createElement('div');
          hint.style.cssText = [
            'position:absolute',
            'bottom:8px',
            'right:8px',
            'opacity:0',
            'transition:opacity 150ms ease',
            'pointer-events:none',
            'font-size:10px',
            'font-family:monospace',
            'background:rgba(0,0,0,0.55)',
            'color:#c9d1d9',
            'border:1px solid rgba(255,255,255,0.12)',
            'border-radius:4px',
            'padding:3px 8px',
            'backdrop-filter:blur(4px)',
          ].join(';');
          hint.textContent = '⤢ Click to expand';
          diagramPanel.appendChild(hint);

          diagramPanel.addEventListener('mouseenter', () => { hint.style.opacity = '1'; });
          diagramPanel.addEventListener('mouseleave', () => { hint.style.opacity = '0'; });

          diagramPanel.addEventListener('click', () => {
            setDiagramSvg(node.innerHTML);
          });
        }
      } catch (renderErr) {
        console.warn(`Mermaid render failed (diagram ${i}):`, renderErr);
        // Show source fallback
        const diagramPanel = node.closest('.diagram-panel') as HTMLElement;
        const sourcePanel = diagramPanel?.nextElementSibling as HTMLElement;
        if (diagramPanel && sourcePanel?.classList.contains('source-panel')) {
          diagramPanel.classList.add('hidden');
          sourcePanel.classList.remove('hidden');
          const btn = diagramPanel.closest('.my-6')?.querySelector('.toggle-btn') as HTMLElement;
          if (btn) btn.textContent = 'View Diagram';
        }
      }

      // Tiny delay between diagrams to let mermaid clean up temp DOM nodes
      if (i < mermaidNodes.length - 1) {
        await new Promise<void>((r) => setTimeout(r, 30));
      }
    }
  } catch (loadErr) {
    console.warn('Failed to load mermaid library:', loadErr);
  }
}

function processCodeCopyButtons(container: HTMLElement) {
  container.querySelectorAll('pre').forEach((pre) => {
    if (
      pre.querySelector('.mermaid-inner') ||
      pre.classList.contains('source-panel') ||
      pre.querySelector('.copy-btn')
    ) return;

    pre.style.position = 'relative';
    pre.classList.add('group');

    const button = document.createElement('button');
    button.className = 'copy-btn absolute top-2.5 right-2.5 p-1.5 rounded-md bg-bg border border-border/50 hover:border-border text-text-dim hover:text-text opacity-0 group-hover:opacity-100 focus:opacity-100 transition-all duration-150 cursor-pointer flex items-center justify-center shadow-sm';
    button.setAttribute('aria-label', 'Copy code');
    button.innerHTML = `<svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3"/></svg>`;

    button.addEventListener('click', () => {
      const text = (pre.querySelector('code')?.textContent ?? pre.textContent) || '';
      navigator.clipboard.writeText(text).then(() => {
        button.innerHTML = `<svg class="w-3.5 h-3.5 text-done" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7"/></svg>`;
        toast.success('Code copied to clipboard');
        setTimeout(() => {
          button.innerHTML = `<svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3"/></svg>`;
        }, 2000);
      });
    });

    pre.appendChild(button);
  });
}

function processLinks(
  container: HTMLElement,
  flatList: FlatItem[],
  router: ReturnType<typeof useRouter>,
) {
  container.querySelectorAll('a[href]').forEach((a) => {
    const href = a.getAttribute('href');
    if (!href || (!href.endsWith('.md') && !href.includes('.md#'))) return;
    const [pathPart, anchorPart] = href.split('#');
    const fname = pathPart.split('/').pop() || '';
    const target = flatList.find((item) => item.path.endsWith(fname));
    if (target) {
      const targetUrl = anchorPart ? `${target.url}#${anchorPart}` : target.url;
      a.addEventListener('click', (e) => {
        e.preventDefault();
        router.push(targetUrl);
      });
    }
  });
}

// ─── Component ────────────────────────────────────────────────────────────────

export function MarkdownRenderer({ html }: MarkdownRendererProps) {
  const containerRef = React.useRef<HTMLDivElement>(null);
  const router = useRouter();
  const flatList = React.useMemo(() => buildFlatList(), []);
  const setDiagramSvg = useUiStore((state) => state.setDiagramSvg);

  // Stable ref so the click handler inside processMermaid always has the
  // latest setDiagramSvg without adding it to the effect deps (which would
  // cause the effect to re-run when the modal closes, wiping rendered SVGs).
  const setDiagramSvgRef = React.useRef(setDiagramSvg);
  React.useEffect(() => { setDiagramSvgRef.current = setDiagramSvg; }, [setDiagramSvg]);

  React.useEffect(() => {
    const container = containerRef.current;
    if (!container) return;

    // rAF ensures dangerouslySetInnerHTML has fully committed to the DOM
    // before we start querying or mutating it.
    const rafId = requestAnimationFrame(() => {
      processMermaid(container, (svg) => setDiagramSvgRef.current(svg));
      processCodeCopyButtons(container);
      processLinks(container, flatList, router);
    });

    return () => cancelAnimationFrame(rafId);
  // setDiagramSvg intentionally excluded — using ref to avoid re-running on modal close
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [html, router, flatList]);

  return (
    <div
      ref={containerRef}
      className="prose-lesson w-full"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
}
